---
layout: page
title: 데이터 과학 -- 기초 통계
subtitle: 실험 유형 구분
output:
  html_document: 
    keep_md: yes
    toc: yes
  pdf_document:
    latex_engine: xelatex
mainfont: NanumGothic
---

``` {r, include=FALSE}
source("tools/chunk-options.R")
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

library(tidyverse)
library(stringr)
library(DT)
library(ggthemes)
library(extrafont)
loadfonts()

options(scipen = 999)
options(dplyr.width = 120)
options(dplyr.print_max = 1e9)
```


## 1. 실험과 관찰 [^coursera-doe]

[^coursera-doe]: [Designing, Running, and Analyzing Experiments](https://www.coursera.org/learn/designexperiments)

김재광 교수님께서 실험 데이터와 관찰 데이터에 대한 차이를 페이스북 담벼락에 사례와 함께 잘 정리해 주셨습니다.

실험 데이터와 관찰 데이터를 구분하는 것은 통계학에서는 가장 기본적인 내용입니다. 
실험은 분석보다는 설계가 어렵고 관찰은 분석이 어렵습니다. 
관찰에서 분석이 어려운 이유는 **중첩요인(confounding factor)**이 존재하기 때문입니다. 
(예를 들어 커피를 마시는 사람들이 암발병률이 높은데 이는 커피 때문이 아니라 커피를 마시는 사람들이 담배를 피우는 경향이 높기 때문입니다. 
  따라서 담배 피는지 여부를 포함해서 분석해야 올바른 결론이 나옵니다.) 
즉, 중첩요인(Confounding factor)을 모형에 포함시켜서 보정해주어야 인과관계에 대해 보다 정확한 결론을 얻을수 있는데, 
문제는 현실적으로 중첩요인을 모두 관측하지 못한다는 것입니다. 
따라서, 중요한 중첩요인을 빼놓고 분석을 하면 잘못된 결론을 얻습니다. 
그래서 과학은 진리라기 보다는 해석에 가깝다고 이야기 할수 있을 것입니다. 
데이터를 바탕으로하고 주관을 최대한 배제한 해석인 것입니다.

<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fjaekwang.kim.125%2Fposts%2F1856505211031977&width=500" width="500" height="382" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>

1. 의학적 지식은 종종 업데이트 된다. 술이 몸에 나쁘다고 했다가 한두잔은 괜찮다고 했다가 또 그것 틀렸다고 했다가 자꾸 바뀐다. 또 물도 많이 먹는게 좋다고 했다가 아니라고 했다가 자꾸 헷갈리게 한다. 왜 그럴까?
1. 두가지 이유를 생각해 볼수 있는데 하나는 관찰연구의 한계이다. 인간을 대상으로는 통제된 실험을 하기 어렵다. (인권 문제 등등 때문에.) 따라서 많은 결론들이 실험이 아닌 관찰 연구 (observational study)를 통해서 얻어지기 때문에 관찰 연구의 한계가 적용된다. 관찰 연구로는 원칙적으로 인과 관계를 규명하는 것이 불가능하다. (그때문에 논문이 자꾸 나올수 있는지도 모르겠다.)
1. 다른 또 하나의 이유는 인간의 생물학적 다양성 때문이다. 인간으로부터 얻어지는 자료는 물리적 자료와는 근본적인 차이가 있는데 그건 같은 인간 종족 내에서도 엄청난 다양성이 있다는 것이다. 기계에서 얻어지는 물리적 자료는 기본적으로 동질적이다. (이는 물리학이나 공대에서 통계학을 우습게 보는것과도 연결되어 있다. physical 한 물질을 대상으로 하는 자료는 샘플링이 필요없다. 자료가 어차피 동질적이므로. ) 하지만 생물학 자료는 그렇지 않다. 똑같은 부모 밑에서도 엄청 다른 자녀가 탄생한다.
1. 따라서 인간을 대상으로 관찰을 하고 이를 통해 일반화를 하는 모든 지식은 어느 정도 한계가 있다는 것을 감안해서 받아 들어야한다. 측정기술이 발달하면 예전에 맞는 것으로 믿어졌던 이론이 틀린 것으로 밝혀진다. 절대적인 지식이 아니라는 것이다. 뇌과학 이런것도 마찬가지.

### 1.1. 비율 검정

| 표본 | 반응 범주 |                     검정                                 |
|------|-----------|----------------------------------------------------------|
|  1   |     2     | 단일 표본 $\chi^2$ 검정, 이항 검정(Binomial Test)    |
|  1   |   2 이상  | 단일 표본 $\chi^2$ 검정, 다항 검정(multinomial Test)     |
| 1이상|   2 이상  | $N$ 표본 $\chi^2$ 검정, G-검정, 피셔의 정확검정      |


### 1.2. 분산 분석과 일반화 선형모형

| 요인  |   수준  | 군간(B)/군내(W) |     모수 검정      |          비모수 검정                 |
|-------|---------|-----------|--------------------------|--------------------------------------|
|  1    |   2     | 군간(B)   | 독립표본 $t-$검정        | 만-위트니 $U$ 검정(Mann-Whitney)     |
|  1    |  2 이상 | 군간(B)   | 일원 분산분석            | 크루스칼-왈리스 검정(Kruskal-Wallis) |
|  1    |    2    | 군간(W)   | 쌍체 $t-$ 검정            | 윌콕슨 부호순위 검정(Wilcoxon signed-rank test)|
|  1    |  2 이상 | 군간(W)   | 일원 반복측정 분산분석   | 프리드만의 검정 (Friedman test)    |
| 1이상 |  2 이상 | 군간(B)   | 요인 분산분석, 선형모형  | Aligned Rank Transform(ART), 일반화선형모형(GLM)|
| 1이상 |  2 이상 | 군간(W)   | 요인 반복측정 분산분석, 선형혼합모형  | Aligned Rank Transform(ART), 일반화선형혼합모형(GLMM)|


## 2. 비율 검정

### 2.1. 사용자 선호도(User Preference) 

* 단일 표본 비율 검정(One-Sample Test of Proportions)
* 단일표본 비율검정 (More One-Sample Tests of Proportions)
* 이표본 비율검정(Two-Sample Tests of Proportions)


### A/B 테스트 -- $t-$검정

* $t-$검정

### 작업 완수 시간 -- 분산분석

* 일원 분산분석 (One-way Analysis of Variance)
    * 군간(Between) 요인 분석

### 사용자 검색 -- 반복 측정

* 반복측정 분산분석(Repeated Measures ANOVA)
    * 군내(Within) 요인 분석

### 핸드폰 자판 입력 -- 요인 실험 설계 

* 요인 실험 설계 (Factorial Design of Experiment)
    * 한가지 이상 요인에 대한 실험 설계

### 일반화 선형 (혼합) 모형

* 일반화 선형 모형(Generalized Linear Models, GLM)
* 일반화 선형 혼합 모형(Generalized Linear Mixed Models, GLMM)


